import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/app/store/provider";
import { LoginButton } from "@/app/components/LoginButton/LoginButton";
import "./global.scss";
import { ReactNode } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <LoginButton />
          {children}
        </body>
      </Providers>
    </html>
  );
}
